name: Unit Tests
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: db0/godot-tester@gut7_3_0
        with:
          version: "3.4.4"
          release_type: "stable"
          path: "."
          test-dir: "res://tests/unit"
          ignore-errors: "true"
          max-fails: 3
          minimum-pass: "0.95"
          assert-check: "true"
